# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(287, 385)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.platformLabel = QtWidgets.QLabel(self.centralwidget)
        self.platformLabel.setObjectName("platformLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.platformLabel)
        self.account_select = QtWidgets.QComboBox(self.centralwidget)
        self.account_select.setObjectName("account_select")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.account_select)
        self.verticalLayout.addLayout(self.formLayout)
        self.signinButton = QtWidgets.QPushButton(self.centralwidget)
        self.signinButton.setObjectName("signinButton")
        self.verticalLayout.addWidget(self.signinButton)
        self.logView = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.logView.setObjectName("logView")
        self.verticalLayout.addWidget(self.logView)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 287, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "oppo采集"))
        self.platformLabel.setText(_translate("MainWindow", "账号"))
        self.signinButton.setText(_translate("MainWindow", "开始"))
